//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Branches
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string Emp_Name { get; set; }
        public string Job { get; set; }
        public string Phone_Num { get; set; }
    
        public virtual sys_branch sys_branch { get; set; }
    }
}
