//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_Cycle
    {
        public int id { get; set; }
        public Nullable<int> device_id { get; set; }
        public string dev_SN { get; set; }
        public Nullable<int> HDR_ID { get; set; }
        public Nullable<int> DocType_ID { get; set; }
        public string To_SIte { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual STK_HDR STK_HDR { get; set; }
        public virtual sys_devices sys_devices { get; set; }
        public virtual sys_doc_type sys_doc_type { get; set; }
    }
}
