//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int id { get; set; }
        public string app_Name { get; set; }
        public string ver { get; set; }
        public Nullable<System.DateTime> ver_date { get; set; }
        public string update_path { get; set; }
    }
}
