//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobDBEntities : DbContext
    {
        public JobDBEntities()
            : base("name=JobDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STK_DTL> STK_DTL { get; set; }
        public virtual DbSet<STK_HDR> STK_HDR { get; set; }
        public virtual DbSet<sys_AreaMgrs> sys_AreaMgrs { get; set; }
        public virtual DbSet<sys_branch> sys_branch { get; set; }
        public virtual DbSet<sys_Category> sys_Category { get; set; }
        public virtual DbSet<sys_connection_type> sys_connection_type { get; set; }
        public virtual DbSet<sys_Dept> sys_Dept { get; set; }
        public virtual DbSet<sys_dev_model> sys_dev_model { get; set; }
        public virtual DbSet<sys_dev_type> sys_dev_type { get; set; }
        public virtual DbSet<sys_devices> sys_devices { get; set; }
        public virtual DbSet<sys_doc_type> sys_doc_type { get; set; }
        public virtual DbSet<sys_status> sys_status { get; set; }
        public virtual DbSet<sys_Type> sys_Type { get; set; }
        public virtual DbSet<sys_Users> sys_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
