//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_HDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STK_HDR()
        {
            this.device_Cycle = new HashSet<device_Cycle>();
            this.STK_DTL = new HashSet<STK_DTL>();
        }
    
        public int HDR_ID { get; set; }
        public string from_Site_Num { get; set; }
        public string from_Site_Name { get; set; }
        public string to_Site_Num { get; set; }
        public string to_Site_Name { get; set; }
        public Nullable<int> doc_type_id { get; set; }
        public string userName { get; set; }
        public Nullable<int> userCode { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<int> Emp_Code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_Cycle> device_Cycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STK_DTL> STK_DTL { get; set; }
        public virtual sys_doc_type sys_doc_type { get; set; }
    }
}
