//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_DTL
    {
        public int DTL_ID { get; set; }
        public int HDR_ID { get; set; }
        public Nullable<int> Device_id { get; set; }
        public string model_Name { get; set; }
        public string item_Code { get; set; }
        public string device_name { get; set; }
        public string device_SN { get; set; }
        public string note { get; set; }
    
        public virtual STK_HDR STK_HDR { get; set; }
        public virtual sys_devices sys_devices { get; set; }
    }
}
