//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_Users()
        {
            this.sys_branch = new HashSet<sys_branch>();
            this.TonerReports = new HashSet<TonerReports>();
            this.TransActions = new HashSet<TransActions>();
        }
    
        public int User_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> JobCode { get; set; }
        public Nullable<bool> mustPassChange { get; set; }
        public Nullable<bool> accountDisabled { get; set; }
        public Nullable<bool> brWin { get; set; }
        public Nullable<bool> brNewbtn { get; set; }
        public Nullable<bool> brEditbtn { get; set; }
        public Nullable<bool> brDeletebtn { get; set; }
        public Nullable<bool> deptWin { get; set; }
        public Nullable<bool> deptNewbtn { get; set; }
        public Nullable<bool> deptEditbtn { get; set; }
        public Nullable<bool> deptDeletebtn { get; set; }
        public Nullable<bool> usrWin { get; set; }
        public Nullable<bool> usrNewbtn { get; set; }
        public Nullable<bool> usrEditbtn { get; set; }
        public Nullable<bool> usrDeletebtn { get; set; }
        public Nullable<bool> catWin { get; set; }
        public Nullable<bool> catNewbtn { get; set; }
        public Nullable<bool> catEditbtn { get; set; }
        public Nullable<bool> catDeletebtn { get; set; }
        public Nullable<bool> devTypeWin { get; set; }
        public Nullable<bool> devTypeNewbtn { get; set; }
        public Nullable<bool> devTypeEditbtn { get; set; }
        public Nullable<bool> devTypeDeletebtn { get; set; }
        public Nullable<bool> mdlWin { get; set; }
        public Nullable<bool> mdlNewbtn { get; set; }
        public Nullable<bool> mdlEditbtn { get; set; }
        public Nullable<bool> mdlDeletebtn { get; set; }
        public Nullable<bool> typeWin { get; set; }
        public Nullable<bool> typeNewbtn { get; set; }
        public Nullable<bool> typeEditbtn { get; set; }
        public Nullable<bool> typeDeletebtn { get; set; }
        public Nullable<bool> statWin { get; set; }
        public Nullable<bool> statNewbtn { get; set; }
        public Nullable<bool> statEditbtn { get; set; }
        public Nullable<bool> statDeletebtn { get; set; }
        public Nullable<bool> devWin { get; set; }
        public Nullable<bool> devNewbtn { get; set; }
        public Nullable<bool> devEditbtn { get; set; }
        public Nullable<bool> devDeletebtn { get; set; }
        public Nullable<bool> transoutWin { get; set; }
        public Nullable<bool> transInWin { get; set; }
        public Nullable<bool> transReportWin { get; set; }
        public Nullable<bool> transReportDeletebtn { get; set; }
        public Nullable<bool> stock { get; set; }
        public Nullable<bool> feedBackMgr { get; set; }
        public string Authority { get; set; }
        public Nullable<bool> PhoneWin { get; set; }
        public Nullable<bool> phoneNewbtn { get; set; }
        public Nullable<bool> phoneEditbtn { get; set; }
        public Nullable<bool> phoneDeletebtn { get; set; }
        public Nullable<bool> TonerWin { get; set; }
        public Nullable<bool> TonerReportWin { get; set; }
        public Nullable<bool> DevCycleReportWin { get; set; }
        public Nullable<bool> DevReportWin { get; set; }
        public Nullable<bool> MaintenanceWin { get; set; }
        public Nullable<bool> DepreciationWin { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<bool> ContactBranchesWin { get; set; }
        public Nullable<bool> Thechnical { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_branch> sys_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonerReports> TonerReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransActions> TransActions { get; set; }
    }
}
