//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dev_model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_dev_model()
        {
            this.sys_devices = new HashSet<sys_devices>();
        }
    
        public int model_id { get; set; }
        public string Name { get; set; }
        public string Item_Code { get; set; }
        public Nullable<int> devType_ID { get; set; }
        public Nullable<int> category_ID { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual sys_Category sys_Category { get; set; }
        public virtual sys_dev_type sys_dev_type { get; set; }
        public virtual sys_Type sys_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_devices> sys_devices { get; set; }
    }
}
