//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_devices()
        {
            this.device_Cycle = new HashSet<device_Cycle>();
            this.STK_DTL = new HashSet<STK_DTL>();
        }
    
        public int Device_id { get; set; }
        public string Name { get; set; }
        public string SN { get; set; }
        public Nullable<int> model_id { get; set; }
        public Nullable<int> dev_Type_id { get; set; }
        public Nullable<int> category_ID { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public Nullable<System.DateTime> opr_date { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_Cycle> device_Cycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STK_DTL> STK_DTL { get; set; }
        public virtual sys_branch sys_branch { get; set; }
        public virtual sys_Category sys_Category { get; set; }
        public virtual sys_Dept sys_Dept { get; set; }
        public virtual sys_dev_model sys_dev_model { get; set; }
        public virtual sys_dev_type sys_dev_type { get; set; }
        public virtual sys_status sys_status { get; set; }
        public virtual sys_Type sys_Type { get; set; }
    }
}
