//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_branch()
        {
            this.sys_Dept = new HashSet<sys_Dept>();
            this.sys_devices = new HashSet<sys_devices>();
            this.sys_phone = new HashSet<sys_phone>();
            this.TonerReports = new HashSet<TonerReports>();
            this.Contact_Branches = new HashSet<Contact_Branches>();
        }
    
        public int branch_id { get; set; }
        public string shrt_id { get; set; }
        public string name { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<bool> Main_Store { get; set; }
    
        public virtual sys_Users sys_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_Dept> sys_Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_devices> sys_devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_phone> sys_phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonerReports> TonerReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Branches> Contact_Branches { get; set; }
    }
}
