//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_phone
    {
        public int phone_id { get; set; }
        public string simcard { get; set; }
        public string simCardSerial { get; set; }
        public string LandLine { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string note { get; set; }
        public string Quota { get; set; }
    
        public virtual sys_branch sys_branch { get; set; }
    }
}
