//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonerReports
    {
        public string ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Toner_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<System.DateTime> First_Date { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Notes { get; set; }
    
        public virtual sys_branch sys_branch { get; set; }
        public virtual sys_Toners sys_Toners { get; set; }
        public virtual sys_Users sys_Users { get; set; }
    }
}
