//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othaim_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransActions
    {
        public int id { get; set; }
        public string IP_PC { get; set; }
        public string user_name_PC { get; set; }
        public string host_name_PC { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual sys_Users sys_Users { get; set; }
    }
}
